name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal es diferente, por ejemplo, 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Cambia esto si es necesario

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material  # Incluye cualquier otra dependencia que uses

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Build and deploy
      run: |
        mkdocs gh-deploy --force
